# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mediafile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='engine',
            field=models.CharField(choices=[(b'redtube', 'Redtube'), (b'xvideos', 'XVideos')], max_length=20),
        ),
    ]
