# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170910_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time of record creation', verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time of last record update', verbose_name='Update Date'),
        ),
    ]
